version: '3'

services:
  api:
    image: try-grapql
    build: 
      context: ./api
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  
  db:
    container_name: db
    restart: always
    image: postgresql
    build:
      context: ./db
    env_file:
      - ./.env
    volumes:
      - ./db/data/:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - psql-pgql
    
  graphql:
    container_name: pgql
    restart: always
    image: graphile/postgraphile
    depends_on:
      - db
    expose:
      - 5000
    ports: 
      - 5000:5000
    env_file:
        - .env
    # environment:
    #   DATABASE_URL: postgres://postgres:1234@db:5432/db
    command: ["postgraphile", "--connection", "${DATABASE_URL}", "--host", "0.0.0.0", "--port", "5000", "--schema", "app_public", "--enhance-graphiql", "--dynamic-json"]
    links:
      - db
    networks:
      - psql-pgql

networks:
  psql-pgql:

# volumes:
#   my-db-volume: